### ISSUE TITLE
Added LND Node But Displays as Unknown

### ISSUE THREAD

**Issue by robbie2121** [janoside/lnd-admin#33]
**Describe the bug**
LND Node that was added has status "Active" but it displays as "unknown"

**Environment (please complete the following information):**
 - LND Version: v0.6-beta-rc4
 - NodeJS Version: node-v10.15.3-x64
 - Browser: google chrome
 - OS: windows 10 64 bit

**To Reproduce**
1. Go to: 127.0.0.1:3004
2. add a lnd node by clicking File Input tab
3. Host field, enter in IP address of my other pc that is hosting lnd node. (example: 192.168.0.10)
4. Port field: keep same
5. Admin Macaroon Filepath field, enter in: \\192.168.0.10\mainnet\admin.macaroon
6; TLS Certificate Filepath field, enter in: \\192.168.0.10\Lnd\tls.cert

\\192.168.0.10\mainnet\admin.macaroon & \\192.168.0.10\Lnd\tls.cert are folders shared to the network from the 192.168.0.10 computer.

**Screenshots or Log Output**
C:\Users\username\AppData\Roaming\npm\node_modules\lnd-admin\views\node.pug:27 25| small.text-monospace.word-wrap.mr-2(style="width: 100%;") #{nodePubkey} 26| > 27| if (nodePubkey == lndRpc.internal_pubkey) 28| i.fas.fa-certificate.fa-xs.text-primary(title="These are the public node details for your active LND node" data-toggle="tooltip") 29| 30| if (utils.isObjectStarred(`node:${node_pubkey}`)) Cannot read property 'internal_pubkey' of undefined

TypeError: C:\Users\username\AppData\Roaming\npm\node_modules\lnd-admin\views\node.pug:27
    25| 		small.text-monospace.word-wrap.mr-2(style="width: 100%;") #{nodePubkey}
    26| 
  > 27| 		if (nodePubkey == lndRpc.internal_pubkey)
    28| 			i.fas.fa-certificate.fa-xs.text-primary(title="These are the public node details for your active LND node" data-toggle="tooltip")
    29| 
    30| 		if (utils.isObjectStarred(`node:${node_pubkey}`))

Cannot read property 'internal_pubkey' of undefined
    at eval (eval at wrap (C:\Users\username\AppData\Roaming\npm\node_modules\lnd-admin\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1375:27)
    at template (eval at wrap (C:\Users\username\AppData\Roaming\npm\node_modules\lnd-admin\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:5541:50)
    at Object.exports.renderFile (C:\Users\username\AppData\Roaming\npm\node_modules\lnd-admin\node_modules\pug\lib\index.js:427:38)
    at Object.exports.renderFile (C:\Users\username\AppData\Roaming\npm\node_modules\lnd-admin\node_modules\pug\lib\index.js:417:21)
    at exports.__express (C:\Users\username\AppData\Roaming\npm\node_modules\lnd-admin\node_modules\pug\lib\index.js:464:11)
    at View.app.engine (C:\Users\username\AppData\Roaming\npm\node_modules\lnd-admin\app.js:63:23)
    at View.render (C:\Users\username\AppData\Roaming\npm\node_modules\lnd-admin\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\username\AppData\Roaming\npm\node_modules\lnd-admin\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\username\AppData\Roaming\npm\node_modules\lnd-admin\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\username\AppData\Roaming\npm\node_modules\lnd-admin\node_modules\express\lib\response.js:1008:7)

**Additional context**

**Comment by robbie2121** [comment]
i can connect a node on the same computer with LNDconnect from the zap wallet. but when i try to add a node on a different computer, it displays as unknown. I think it has something to do with each computer running a vpn client.

**Comment by janoside** [comment]
Got this figured out? Anything that needs to be addressed in the project?

**Comment by robbie2121** [comment]
I haven't but i'm sure it has more to do with each computer running their own individual vpn client which is doing something to the lan connection. I haven't tried yet when turning off the VPN on one computer. When I try, I can reply back with result.

**Comment by janoside** [comment]
Great, thanks. Being a new project I want to do my best to see that people aren't getting stuck, especially at the starting line.
